# Generated by Django 3.0.8 on 2021-01-02 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Charpter',
            fields=[
                ('charpterid', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('sid', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'charpter',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Novel',
            fields=[
                ('novelid', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.IntegerField()),
                ('sort', models.CharField(blank=True, max_length=100, null=True)),
                ('novelname', models.CharField(blank=True, max_length=100, null=True)),
                ('novelimg', models.CharField(blank=True, max_length=200, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=40, null=True)),
                ('author', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 'novel',
                'managed': False,
            },
        ),
    ]
